version: "2"

services:

  pmda1:
    image: kokardy/rproxy
    restart: always
    ports:
      - "8081:80"
    environment:
      - "SCHEME=http"
      - "RHOST=www.pmda.go.jp"
      - "ADDR=:80"
      - "ORI=www.info.pmda.go.jp"
      - "DEST=10.26.61.131:9081"
    extra_hosts:
        - www.pmda.go.jp:103.28.167.217
        - www.info.pmda.go.jp:220.216.69.145

  pmda2:
    image: kokardy/rproxy
    restart: always
    ports:
      - "9081:80"
    environment:
      - "SCHEME=http"
      - "RHOST=www.info.pmda.go.jp"
      - "ADDR=:80"
      - "ORI=www.pmda.go.jp"
      - "DEST=10.26.61.131:8081"
    extra_hosts:
        - www.pmda.go.jp:103.28.167.217
        - www.info.pmda.go.jp:220.216.69.145

  pmda-kv:
    image: kokardy/pmda-kv
    restart: always
    ports:
      - "8082:80"

  medmst:
    image: kokardy/medmst-sv:latest
    #build: ./medmst-sv
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - "PG_HOST=postgres"
      - "PG_PORT=5432"
      - "PG_USER=postgres"
      - "PG_PASSWORD=allyourbaseisbelongtous"
      - "PG_DATABASE=medmst"
    links:
      - postgres
    env_file: .env
    volumes:
      - ./medmst-sv/asset:/asset

  postgres:
    image: postgres:9.5-alpine
    restart: always
    #ports:
    #    - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=allyourbaseisbelongtous"
      - "POSTGRES_USR=postgres"

    volumes:
      - ./pg/initdb:/docker-entrypoint-initdb.d
