version: "2"

services:

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8081:80"
    env_file: .env
    volumes:
      - ./nginx:/etc/nginx
#    dns: 8.8.8.8
    extra_hosts:
        - www.pmda.go.jp:103.28.167.217

  pmda-kv:
    image: kokardy/pmda-kv
    restart: always
    ports:
      - "8082:80"

  medmst:
    image: kokardy/medmst-sv:latest
    #build: ./medmst-sv
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - "PG_HOST=postgres"
      - "PG_PORT=5432"
      - "PG_USER=postgres"
      - "PG_PASSWORD=allyourbaseisbelongtous"
      - "PG_DATABASE=medmst"
    links:
      - postgres
    env_file: .env
    volumes:
      - ./medmst-sv/asset:/asset

  postgres:
    image: postgres:9.5-alpine
    restart: always
    #ports:
    #    - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=allyourbaseisbelongtous"
      - "POSTGRES_USR=postgres"

    volumes:
      - ./pg/initdb:/docker-entrypoint-initdb.d
