version: "2"

services:

  medmst:
    image: kokardy/medmst-sv
    #restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - "PG_HOST=postgres"
      - "PG_PORT=5432"
      - "PG_USER=postgres"
      - "PG_PASSWORD=allyourbaseisbelongtous"
      - "PG_DATABASE=medmst"
    links:
      - postgres
    env_file: .env

  postgres:
    image: postgres:9.5-alpine
    restart: always
    #ports:
    #    - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=allyourbaseisbelongtous"
      - "POSTGRES_USR=postgres"

    volumes:
      - ./pg/initdb:/docker-entrypoint-initdb.d
