version: "2"

services:

  pmda-kv:
    image: kokardy/pmda-kv
    restart: always
    env_file: .env
    ports:
      - "8082:80"

  medmst:
    image: kokardy/medmst-sv:latest
    #build: ./medmst-sv
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - "PG_HOST=postgres"
      - "PG_PORT=5432"
      - "PG_USER=postgres"
      - "PG_PASSWORD=allyourbaseisbelongtous"
      - "PG_DATABASE=medmst"
      - "ADMIN_USER=di"
      - "ADMIN_PASSWORD=diwindow1235"
    links:
      - postgres
    env_file: .env
    volumes:
      - ./medmst-sv/asset:/asset
      - ./backup:/backup

  backuper:
    image: kokardy/medmst-sv:latest
    restart: always
    environment:
      - "TZ=Asia/Tokyo"
      - "PG_HOST=postgres"
      - "PG_PORT=5432"
      - "PG_USER=postgres"
      - "PG_PASSWORD=allyourbaseisbelongtous"
      - "PG_DATABASE=medmst"
      - "ADMIN_USER=di"
      - "ADMIN_PASSWORD=diwindow1235"
    links:
      - postgres
    env_file: .env
    volumes_from:
        - medmst
    command: ["/asset/cron.sh"]

  postgres:
    image: postgres:9.5-alpine
    restart: always
    #ports:
    #    - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=allyourbaseisbelongtous"
      - "POSTGRES_USR=postgres"

    volumes:
      - ./pg/initdb:/docker-entrypoint-initdb.d
