version: "2"

services:

  #  pmda:
  #    image: nginx
  #    restart: always
  #    ports:
  #      - "8081:8081"
  #    env_file: .env
  #    volumes:
  #      - ./nginx:/etc/nginx

  pmda:
    #image: kokardy/rproxy
    build:
      context: ./rproxy
      args:
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
        - "HTTP_PROXY=${http_proxy}"
        - "HTTPS_PROXY=${https_proxy}"
    restart: always
    ports:
      - "8081:80"
    env_file: .env
    environment:
      - "SCHEME=https"
      - "RHOST=www.pmda.go.jp"
      - "ADDR=:80"
      - "ORI=(https?:)?//www\\.info\\.pmda\\.go\\.jp"
      - "DEST=//10.26.61.131:9081"
      - "ORI2=(https?:)?//www\\.pmda\\.go\\.jp"
      - "DEST2=//10.26.61.131:8081"

  pmda-info:
    #image: kokardy/rproxy
    build:
      context: ./rproxy
      args:
        - "http_proxy=${http_proxy}"
        - "https_proxy=${https_proxy}"
        - "HTTP_PROXY=${http_proxy}"
        - "HTTPS_PROXY=${https_proxy}"
    restart: always
    ports:
      - "9081:80"
    env_file: .env
    environment:
      - "SCHEME=https"
      - "RHOST=www.info.pmda.go.jp"
      - "ADDR=:80"
      - "ORI=(https?:)?//www\\.info\\.pmda\\.go\\.jp"
      - "DEST=//10.26.61.131:9081"
      - "ORI2=(https?:)?//www\\.pmda\\.go\\.jp"
      - "DEST2=//10.26.61.131:8081"
