version: "2"

services:

  pmda:
    image: nginx
    restart: always
    ports:
      - "8081:8081"
    env_file: .env
    volumes:
      - ./nginx:/etc/nginx

  pmda-info:
    image: kokardy/rproxy
    restart: always
    ports:
      - "9081:80"
    env_file: .env
    environment:
      - "SCHEME=https"
      - "RHOST=www.info.pmda.go.jp"
      - "ADDR=:80"
